# Workspace subgroup

Generated map of this subgroup: its directory structure, each repo's purpose
inlined, child subgroups inlined recursively. Regenerated by the `control`
repo's `workspace` profile. See [control](https://gitlab.com/konradodwrot/control).

@assets/data/repo-index.md
