# Workspace subgroup

Generated map of this subgroup: its directory structure, each repo's purpose
inlined, child subgroups inlined recursively. Regenerated by the `automation`
repo's `workspace` profile. See [automation](https://gitlab.com/konradodwrot/cross-repo/automation).

@assets/data/repo-index.md
