#!/bin/zsh
#>[what]
#   generate each subgroup's repo-index + rendered AGENTS.md/CLAUDE.md for every
#   subgroup dir under $WORKSPACE_DIR (the workspace root down through all groups)
#/[what]

emulate -LR zsh
setopt errexit pipefail
umask 002

##[>] 🤖🤖🤖
#[why] environments without che (image bakes) skip
if ! (( $+commands[che] )) {
  print -r -- "index: skip: che not found"
  return 0
}

#[what] the top index lists each group's host dir, then every subgroup below
typeset root=${WORKSPACE_DIR:-$HOME/projects/gitlab}
typeset tpl=${0:A:h}/../templates/subgroup-index.md.ontoRepo.tpl

#[why] che render repo-group-index owns discovery; here we drive one run per subgroup
function has_repo_below {
  local hits=($1/.git(N/) $1/**/.git(N/))
  (( $#hits ))
}

function inline_index {
  local dir=$1 body=$2
  print -r -- $body | while IFS= read -r line; do
    if [[ $line == '@assets/data/repo-index.md' ]]; then
      cat ${dir}/assets/data/repo-index.md
    else
      print -r -- $line
    fi
  done
}

function index_subgroup {
  local dir=$1
  local data=${dir}/assets/data
  local header="<!-- autogenerated using workspace/templates/subgroup-index.md.ontoRepo.tpl -->"
  local body=$( cd $dir && che render tpl -f $tpl )
  if [[ -d ${dir}/assets/.git ]] {
    local index=$(che render repo-group-index $dir)
    print -r -- $header > ${dir}/CLAUDE.md
    print -r -- ${body/@assets\/data\/repo-index.md/$index} >> ${dir}/CLAUDE.md
    cp ${dir}/CLAUDE.md ${dir}/AGENTS.md
    print -r -- "index: $dir (inlined: assets/ is a repo)"
    return 0
  }
  mkdir -p $data
  che render repo-group-index $dir > ${data}/repo-index.md
  print -r -- $header > ${dir}/CLAUDE.md
  print -r -- $body >> ${dir}/CLAUDE.md
  print -r -- $header > ${dir}/AGENTS.md
  inline_index $dir $body >> ${dir}/AGENTS.md
  print -r -- "index: $dir"
}

#[why] every branch returns explicitly: under errexit a trailing failed test (no subgroup here, e.g. a
#   workspace not cloned yet) would otherwise return non-zero and abort the whole run
function walk {
  local dir=$1
  if [[ -d $dir/.git ]] return 0
  local child is_subgroup=0
  for child in $dir/*(N/); do
    if { has_repo_below $child } { is_subgroup=1; walk $child }
  done
  if (( is_subgroup )) index_subgroup $dir
  return 0
}

function write_code_workspace {
  local out=${root}/gitlab.code-workspace repo rel
  local -a repos=(${root}/**/.git(N/:h))
  [[ -L $out ]] && command rm -f $out
  {
    print '{'
    print '  "folders": ['
    local i=0
    for repo in ${(o)repos}; do
      rel=${repo#${root}/}
      (( i++ )) && print ','
      print -rn -- "    { \"name\": \"${rel#*/}\", \"path\": \"${rel}\" }"
    done
    print ''
    print '  ],'
    print '  "settings": {}'
    print '}'
  } > $out
  print -r -- "index: $out (${#repos} repos)"
}

walk $root
write_code_workspace
##[<] 🤖🤖🤖
